name: My second workflow
on: push

jobs: 
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: checkout repo files
        run: ls -lrtha .github/workflows

      - name: Executing shell Script
        run: |
         sudo apt-get install cowsay -y
         cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - uses: actions/upload-artifact@v4
        with:
            name: dragon.txt
            path:  /home/runner/work/actions-1/actions-1/dragon.txt # or path/to/artifact
      
      - name: Sleep 30 seconds
        run: sleep 30

  test_job_2:
    runs-on: ubuntu-latest
    needs: build_job_1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dragon.txt
          path:  /home/runner/work/actions-1/actions-1/dragon.txt  
      - name: Sleep for 10 secs
        run: sleep 10
    
      - name: Test file exists
        run: grep -i "DRAGON"  /home/runner/work/actions-1/actions-1/dragon.txt
      


  deploy_job_3:
    runs-on: ubuntu-latest
    needs: [build_job_1,test_job_2]
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: dragon.txt
        path:  /home/runner/work/actions-1/actions-1/dragon.txt 
    - name: Read file
      run: cat  /home/runner/work/actions-1/actions-1/dragon.txt 
    - name: Deploy
      run: echo "Deploying..."